services:
  - type: web
    name: gmail-individual-sender
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 600 --workers 1
    autoDeploy: true
